Repository honeycombio/libhoney-py, pull requests merged in 2024-03, with the labels that each got.

#231 feat: support classic-flavored ingest keys
  libhoney/__init__.py
  libhoney/client.py
  libhoney/test_client.py
Labels: type: enhancement, version: bump minor, merge at will

#232 rel: v2.4.0
  .bumpversion.cfg
  CHANGELOG.md
  libhoney/version.py
  poetry.lock
  pyproject.toml
Labels: no-changelog

#233 maint: add labels to release.yml for auto-generated grouping
  .github/release.yml
Labels: version: no bump, type: maintenance, no-changelog
